apiVersion: v1
data:
  api-key: PERBVEFET0dfQVBJX0tFWT4=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: ''
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: -datadog
    app.kubernetes.io/version: '7'
    helm.sh/chart: datadog-2.6.0
  name: -datadog
type: Opaque
